@extends('layouts.app')
@section('title','My study notes')
@section('content')<div class="page-heading">
<div>
<span class="eyebrow">LESS NOISE. MORE UNDERSTANDING.</span>
<h1>Your personal notes library.</h1>
<p class="muted">A clearer view of what you’re learning. Visible only to you.</p>
</div>
<a class="button" href="{{ route('courses.index') }}">Choose course content ↗</a>
</div>
<div class="notice">✧ {{ config('study.provider')==='mock' ? 'Development mock is enabled. These sample notes are not generated by an AI model.' : 'AI-generated notes may contain mistakes. Always check the original course material.' }} Generate notes from a lesson or supported material inside an enrolled course.</div>
<div class="course-grid">@forelse($notes as $note)<article class="panel note-card">
<div class="row between">
<span class="big-spark">✧</span>
<span class="badge {{ $note->status }}">{{ ucfirst($note->status) }}</span>
</div>
<h3>
<a href="{{ route('notes.show',$note) }}">{{ $note->title }}</a>
</h3>
<p class="muted">Source: {{ $note->source_title }}</p>
<small>{{ $note->created_at->format('M j, Y') }} · {{ $note->provider==='mock' ? 'Development mock' : 'AI-generated' }}</small>
<div class="card-action">
<a href="{{ route('notes.show',$note) }}">Open note →</a>
</div>
</article>@empty<section class="empty panel">
<span class="big-spark">✧</span>
<h2>A fresh page for your ideas.</h2>
<p>Open a course, select a lesson, and generate your first set of study notes.</p>
<a href="{{ route('courses.index') }}">Explore your courses →</a>
</section>@endforelse</div>{{ $notes->links() }}@endsection
