@extends('layouts.app')
@section('title', 'AI administration')
@section('content')
<h1>AI administration</h1><p class="muted">OpenRouter requests permit only zero-price models, deny data collection, require zero data retention, and disable fallback. Availability may be limited by these restrictions.</p>
<form class="panel" method="post" action="{{ route('admin.ai.update') }}">@csrf @method('put')<input type="hidden" name="version" value="{{ $safe['version'] }}">
<label>AI features<select name="enabled"><option value="1" @selected($safe['enabled'])>Enabled</option><option value="0" @selected(!$safe['enabled'])>Disabled</option></select></label>
<label>Provider<select name="provider">@foreach(['mock' => 'Development mock (no AI service)', 'openrouter' => 'OpenRouter (free models only)', 'openai' => 'OpenAI (explicit paid use)'] as $value => $label)<option value="{{ $value }}" @selected($safe['provider'] === $value)>{{ $label }}</option>@endforeach</select></label>
<label>Model<input name="model" list="ai-models" value="{{ old('model', $safe['model']) }}" maxlength="200"></label><datalist id="ai-models">@foreach($models as $id => $name)<option value="{{ $id }}">{{ $name }}</option>@endforeach</datalist><p class="muted">Free-model catalog refreshed: {{ $catalogAt ?? 'Not yet refreshed' }}. Refresh before selecting an OpenRouter model.</p>
<label>Replace API credential<input type="password" name="api_key" autocomplete="new-password" maxlength="4096"></label><p class="muted">{{ $hasKey ? 'A credential is configured. Leave blank to retain it for the same provider.' : 'No credential configured.' }}</p><label><input type="checkbox" name="remove_key" value="1"> Remove stored credential</label>
<label>Requests per user per day (UTC)<input type="number" name="daily_limit" min="1" max="100" value="{{ $safe['daily_limit'] }}" required></label><label>Maximum input characters<input type="number" name="max_input_chars" min="1000" max="40000" value="{{ $safe['max_input_chars'] }}" required></label><label>Maximum output tokens<input type="number" name="max_output_tokens" min="256" max="4000" value="{{ $safe['max_output_tokens'] }}" required></label><label><input type="checkbox" name="allow_paid" value="1"> I explicitly approve paid OpenAI usage if OpenAI is enabled.</label><button class="button">Save AI settings</button></form>
<div class="two-col"><form class="panel" method="post" action="{{ route('admin.ai.models') }}">@csrf<button class="button secondary">Refresh OpenRouter free models</button></form><form class="panel" method="post" action="{{ route('admin.ai.test') }}">@csrf<button class="button secondary">Test saved credentials</button><p class="muted">Checks authentication without sending course content or requesting inference.</p></form></div>
<section class="panel"><h2>Recent AI activity</h2>@forelse($usage as $event)<p>{{ $event->provider }} · {{ $event->model }} · {{ $event->status }} · {{ $event->input_chars }} input characters · {{ $event->created_at }} UTC</p>@empty<p>No recorded requests yet.</p>@endforelse{{ $usage->links() }}</section>
@endsection
